### ISSUE TITLE
starting container process caused: exec: "/entrypoint.sh": permission denied: unknown.

### ISSUE THREAD

**Issue by insign** [yassinebridi/pushbullet-action#1]
```
Run yassinebridi/pushbullet-action@v1.0.0
  with:
  env:
    PB_TOKEN: ***
    PB_TYPE: link
    PB_TITLE: AMP EasyContent
    PB_BODY: Upload OK
    PB_URL: https://plenamulher.com.br/amp/
/usr/bin/docker run --name a33c175bfffadb49849b99b55b5c3163cb259_7ccf1c --label 8a33c1 --workdir /github/workspace --rm -e PB_TOKEN -e PB_TYPE -e PB_TITLE -e PB_BODY -e PB_URL -e INPUT_PB_TOKEN -e INPUT_PB_TYPE -e INPUT_PB_TITLE -e INPUT_PB_BODY -e INPUT_PB_FILE_NAME -e INPUT_PB_FILE_TYPE -e INPUT_PB_FILE_URL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/easy-amp/easy-amp":"/github/workspace" 8a33c1:75bfffadb49849b99b55b5c3163cb259
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": permission denied: unknown.
time="2021-06-16T15:17:05Z" level=error msg="error waiting for container: context canceled"
```
