### ISSUE TITLE
VScode syntax highlight error, but still runs without problem 

### ISSUE THREAD

**Issue by AristideBH** [yassinebridi/pushbullet-action#3]
I'm using your action to send a link to after  build and deployment has been completed and it works great, thanks you !
However, I'm geting a syntax error in VS Code : 
```
Missing required inputs: `PB_TOKEN`, `PB_TYPE`
```
They're clearly not mising, as the action get executed without any bug. 
Any pointers to why and how I can solve this ?

Here's on I added the action to my build.yml
```yml
name: Build & publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Publish Docker Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}
          containerRegistry: true

      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'redacted'

      - name: Pushbullet Notification
        uses: yassinebridi/pushbullet-action@v1.0.2
        env:
          PB_TOKEN: '${{ secrets.PB_TOKEN }}'
          PB_TYPE: link
          PB_TITLE: Updated !
          PB_BODY: A new version of your site has been built and deployed.
          PB_URL: redacted

```
